language: objective-c
matrix:
    include:
        - osx_image: xcode9.3beta

script:
    - xcodebuild build test -project EmojiSwift.xcodeproj -scheme EmojiSwift -destination "platform=iOS Simulator,name=iPhone X"

